spring:
  application:
    name: spring-cloud-web-admin-feign

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true #开启熔断器